//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblServices
    {
        public int ServicesId { get; set; }
        public string ServicesTitle { get; set; }
        public string ServicesImageUrl { get; set; }
        public string Description { get; set; }
    }
}
