//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevFolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSocialMedia
    {
        public int SocialMediID { get; set; }
        public string PlatformName { get; set; }
        public string IconUrl { get; set; }
        public string RedirectUrl { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
